exclude:
- Gemfile

#Site settings
theme: jekyll-theme-minimal
title: " "
logo: "/valencia_headshot.jpeg"
description: >
 <a href = "https://github.com/ejvalencia"> GitHub </a> | <a href = "https://scholar.google.com/citations?user=_KfuPbwAAAAJ&hl=en&inst=17001591832933267808&oi=ao"> Google Scholar </a> | <a href = "./valencia_cv_01-2022.pdf"> CV </a>
 <br />
 <br />
 Queer PhD Student (They/Them), <br />
 Critical Epidemiologist, <br />
 Social Demographer, <br />
 Prison Abolitionist
lang: en-US
encoding: utf-8
email: "ejvalencia@student.ubc.ca"
url: "https//ejvalencia.github.io/"
