exclude:
- Gemfile

#Site settings
theme: jekyll-theme-minimal
title: " "
logo: "/valencia_headshot.jpeg"
description: >
 <a href = "https://github.com/ejvalencia" target = "_blank"> GitHub </a> | 
 <a href = "https://scholar.google.com/citations?user=_KfuPbwAAAAJ&hl=en&inst=17001591832933267808&oi=ao" target = "_blank"> Google Scholar </a> | 
 <a href = "./valencia_cv_updated.pdf" target = "_blank"> CV </a>
 <br />
 <br />
 Social Epidemiology <br />
 Health Demography <br />
 Geospatial Research Methods <br />
lang: en-US
encoding: utf-8
email: "esteban.valencia@bcchr.ca"
url: "https//ejvalencia.github.io/"
