exclude:
- Gemfile

#Site settings
theme: jekyll-theme-dinky
title: [Title Here]
description:
 Queer PhD Student <br />
 Critical Epidemiology <br />
 Social Demography
show_downloads: TRUE
github:
  cv_url: .valencia_cv-01.2022.pdf
lang: en-US
encoding: utf-8
email: "ejvalencia@ubc.ca"
url: "https//ejvalencia.github.io/"

#plugins:
#- jekyll-sitemap
#- jekyll-mentions
#- jekyll-paginate
#- jekyll-seo-tag
#- jekyll-redirect-from
#- jekyll-default-layout
#- jekyll-feed
#- jemoji
#- jekyll-remote-theme

# Site navigation
navigation_header:
 Home: /
#- title: "CV"
#  url: ./CV.pdf
#- title: "Google Scholar"
#  url: https://scholar.google.com/citations?user=_KfuPbwAAAAJ&hl=en&inst=17001591832933267808&oi=ao">Google Scholar
