exclude:
- Gemfile

#Site settings
theme: jekyll-theme-minimal
title: "Esteban J. Valencia, MPH"
description: >
  <a href="https://scholar.google.com/citations?user=_KfuPbwAAAAJ&hl=en&inst=17001591832933267808&oi=ao">Google Scholar</a>
   Makes a mean cornbread 
encoding: utf-8
lang: en-US
url: "https://ejvalencia.github.io"
#repo: "https://github.com/jlgodwin/jlgodwin.github.io"
email: "ejvalen@student.ubc.ca"
